name: dev meta_emb_va_d table
type: meta # meta/baseline
meta_type: spk

adapt:
    speaker_emb: encoder # shared/table/encoder
    modules:
        - encoder
        - variance_adaptor
        - decoder
        - mel_linear
        - postnet

    ways: 1
    shots: 5
    queries: 5
    steps: 2
    lr: 0.001
    meta_batch_size: 1

    test:
        queries: 1
        steps: 100 # max adaptation steps for testing
