name: dvec_va_d
type: baseline  # meta/baseline

adapt:
  speaker_emb: encoder # shared/table/encoder
  modules:
    - variance_adaptor
    - decoder
    - mel_linear
    - postnet

  ways: 1
  shots: 5
  queries: 5
  steps: 5
  lr: 0.001
  meta_batch_size: 1

  test:
    queries: 1
    steps: 100 # max adaptation steps for testing
