name: ml_meta_dotsim_va_d table
type: ml-meta # meta/baseline

adapt:
    speaker_emb: table # shared/table/encoder
    modules:
        - emb_generator
        - speaker_emb
        - variance_adaptor
        - decoder
        - mel_linear
        - postnet

    ways: 1
    shots: 100
    queries: 100
    steps: 5
    lr: 0.001
    meta_batch_size: 1

    test:
        queries: 100
        steps: 100 # max adaptation steps for testing
